# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  disable:
    - errcheck
    - staticcheck
    - goconst
    - gosec
  enable:
    - govet
    - ineffassign
    - unused
    - misspell
    - unconvert

linters-settings:
  govet:
    shadow: true
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-dirs:
    - vendor
    - .git
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
        - goconst
