title: Stoolap
description: High-performance columnar SQL database written in pure Go
theme: jekyll-theme-minimal
url: https://stoolap.io
domain: stoolap.io
baseurl: "" # Since we're using a custom domain
permalink: pretty
logo: assets/img/logo.svg
github:
  repository_url: https://github.com/stoolap/stoolap

# Google Analytics
google_analytics: 

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore

# Collections for documentation
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag